version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    #network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Asia/Calcutta'
      # FTLCONF_webserver_api_password is the new variable for the password since Pi-hole v6.
      # WEBPASSWORD is for older versions.
      FTLCONF_webserver_api_password: 'newhs@1234'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required to detect service discovery from DHCP servers, not for DNS.
    restart: unless-stopped
