---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

# - Developer:
#     - Github:
#         - abbr: GH
#           href: https://github.com/

# - Social:
#     - Reddit:
#         - abbr: RE
#           href: https://reddit.com/

# - Entertainment:
#     - YouTube:
#         - abbr: YT
#           href: https://youtube.com/

# - General:
#     - Homepage Docs:
#         - abbr: GHP
#           # icon: si-docsify
#           href: https://gethomepage.dev/
#     - Docker Hub:
#         - abbr: GHP
#           # icon: si-docker
#           href: https://hub.docker.com/